/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f446xx.h"

static void GPIO_Config();
static void LockControl();

int main(void)
{
	GPIO_Config();

	GPIO_LockPin(GPIOC, GPIO_PIN_13);

	LockControl();

	//GPIO_WritePin( GPIOB, GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14, GPIO_Pin_Set );

    /* Loop forever */
	for(;;)
	{
		if ( GPIO_ReadPin( GPIOC, GPIO_PIN_13 ) == GPIO_Pin_Set )
		{
			GPIO_WritePin( GPIOB, GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14, GPIO_Pin_Set );
		}
		else
		{
			GPIO_WritePin( GPIOB, GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14, GPIO_Pin_Reset );
		}
	}
}

static void GPIO_Config()
{
	GPIO_InitTypeDef_t GPIO_InitStruct = { 0 };

	RCC_GPIOB_CLK_ENABLE();		/* Clock B is active */
	RCC_GPIOC_CLK_ENABLE();		/* Clock C is active */
	RCC_SYSCFG_CLK_ENABLE();	/* Clock SYSCFG is active */

	GPIO_InitStruct.pinNumber = GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
	GPIO_InitStruct.Speed = GPIO_OSPEED_LOW;
	GPIO_InitStruct.Otype = GPIO_OTYPE_PP;
	GPIO_InitStruct.PuPd = GPIO_PUPD_NOPULL;

	GPIO_Init(GPIOB, &GPIO_InitStruct);

	memset( &GPIO_InitStruct, 0, sizeof(GPIO_InitStruct) );

	GPIO_InitStruct.pinNumber = GPIO_PIN_13;
	GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
	GPIO_InitStruct.PuPd = GPIO_PUPD_PULLDOWN;

	GPIO_Init(GPIOC, &GPIO_InitStruct);

	EXTI_LineConfig(EXTI_PortSource_GPIOC, EXTI_LineSource_7);
}

static void LockControl()
{
	GPIO_InitTypeDef_t GPIO_InitStruct = { 0 };

	GPIO_InitStruct.pinNumber = GPIO_PIN_13;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
	GPIO_InitStruct.PuPd = GPIO_PUPD_NOPULL;

	GPIO_Init(GPIOC, &GPIO_InitStruct);
}
